# Generated by Django 2.1.15 on 2020-11-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rater', '0001_initial'),
        ('raw_data', '0001_initial'),
        ('task', '0001_initial'),
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('parsed_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_tuple_num', models.IntegerField(blank=True, null=True)),
                ('duplicate_tuple_num', models.IntegerField(blank=True, null=True)),
                ('column_null_ratio', models.FloatField(blank=True, null=True)),
                ('quantity_score', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('evaluated', models.IntegerField()),
                ('pass_field', models.IntegerField(db_column='pass')),
                ('rater', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rater.Rater')),
                ('raw_data_seq_file', models.ForeignKey(db_column='raw_data_seq_file', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='raw_data.RawDataSeqFile')),
                ('submitter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='submitter.Submitter')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
            options={
                'db_table': 'parsed_data',
            },
        ),
    ]
