# Generated by Django 2.1.15 on 2020-11-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_data', '0001_initial'),
        ('submitter', '0001_initial'),
        ('rater', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('parsed_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_tuple', models.PositiveIntegerField()),
                ('num_duple', models.PositiveIntegerField()),
                ('percentage_null', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('ordinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_ordinal', to='raw_data.RawData')),
                ('parsed_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raw_data.RawData')),
                ('period_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_end', to='raw_data.RawData')),
                ('period_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_start', to='raw_data.RawData')),
                ('raters', models.ManyToManyField(to='rater.Rater')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter')),
            ],
        ),
    ]
