# Generated by Django 2.1.15 on 2020-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('parsed_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_tuple', models.PositiveIntegerField()),
                ('num_duple', models.PositiveIntegerField()),
                ('percentage_null', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
            ],
        ),
    ]
