# Generated by Django 2.1.15 on 2020-12-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parseddata',
            old_name='pass_field',
            new_name='pass_or_not',
        ),
    ]
