# Generated by Django 3.1.2 on 2020-11-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submitter', '0001_initial'),
        ('parsed_data', '0001_initial'),
        ('task', '0001_initial'),
        ('rater', '0002_rater_rated_tasks'),
        ('raw_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='ordinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_ordinal', to='raw_data.rawdata'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='parsed_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raw_data.rawdata'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='period_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_end', to='raw_data.rawdata'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='period_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_start', to='raw_data.rawdata'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='raters',
            field=models.ManyToManyField(to='rater.Rater'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.submitter'),
        ),
    ]
