# Generated by Django 2.1.15 on 2020-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsed_data', '0001_initial'),
        ('raw_data', '0001_initial'),
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='ordinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_ordinal', to='raw_data.RawData'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='parsed_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raw_data.RawData'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='period_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_end', to='raw_data.RawData'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='period_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brought_period_start', to='raw_data.RawData'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='raters',
            field=models.ManyToManyField(to='rater.Rater'),
        ),
    ]
