# Generated by Django 3.1.2 on 2020-11-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_auto_20201126_2112'),
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='rater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rater.rater'),
        ),
    ]
