# Generated by Django 2.1.15 on 2020-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('submitter', '0001_initial'),
        ('parsed_data', '0002_auto_20201113_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
    ]
