# Generated by Django 2.1.15 on 2020-12-03 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20201204_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='quality_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
