# Generated by Django 2.1.15 on 2020-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_auto_20201204_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='submitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
    ]
