# Generated by Django 3.1.2 on 2020-11-06 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ID',
            field=models.CharField(default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='PW',
            field=models.CharField(default='na', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='na', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='01012343434', max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('R', 'Rater'), ('S', 'Submitter')], default='na', max_length=10),
        ),
    ]
