# Generated by Django 2.1.15 on 2020-11-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_admin', '0001_initial'),
        ('submitter', '0001_initial'),
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('submitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('min_cycle', models.DurationField()),
                ('creator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_admin.MyAdmin')),
                ('participants', models.ManyToManyField(through='task.Participate', to='submitter.Submitter')),
                ('raters', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rater.Rater')),
            ],
        ),
        migrations.AddField(
            model_name='participate',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
