# Generated by Django 2.1.15 on 2020-11-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTask',
            fields=[
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='submitter.Submitter')),
                ('approved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apply_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('mincycle', models.IntegerField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
