# Generated by Django 2.1 on 2020-11-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_remove_rater_rated_tasks'),
        ('my_admin', '0001_initial'),
        ('submitter', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('submitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter')),
            ],
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_admin.MyAdmin'),
        ),
        migrations.AddField(
            model_name='task',
            name='raters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rater.Rater'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participate',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(through='task.Participate', to='submitter.Submitter'),
        ),
    ]
