# Generated by Django 2.1 on 2020-12-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_pass_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchema',
            fields=[
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='task.Task')),
                ('TaskDataTableName', models.CharField(max_length=100)),
                ('TaskDataTableScheme', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'task_schema',
            },
        ),
    ]
