# Generated by Django 2.1.15 on 2020-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDataTableSchema',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=30, unique=True)),
                ('field_type', models.CharField(choices=[('char', 'Char'), ('int', 'Int'), ('date', 'Date'), ('boolean', 'Boolean')], default='na', max_length=30)),
                ('null_valid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='na', max_length=30)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
            options={
                'db_table': 'task_data_table_schema',
            },
        ),
        migrations.AlterField(
            model_name='applytask',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
    ]
