# Generated by Django 2.1.15 on 2020-11-29 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_admin',
            },
        ),
        migrations.CreateModel(
            name='TaskCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Comment', models.CharField(max_length=100)),
                ('mincycle', models.IntegerField(default=0)),
                ('TaskDataTableName', models.CharField(max_length=100)),
                ('TaskDataTableScheme', models.CharField(max_length=100)),
            ],
        ),
    ]
