# Generated by Django 2.1.15 on 2020-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Comment', models.CharField(max_length=100)),
                ('TaskDataTableName', models.CharField(max_length=100)),
                ('TaskDataTableScheme', models.CharField(max_length=100)),
            ],
        ),
    ]
