# Generated by Django 2.1 on 2020-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreate',
            name='TaskDataTableScheme',
            field=models.CharField(max_length=10000),
        ),
    ]
