# Generated by Django 2.1.15 on 2020-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201113_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID',
            field=models.CharField(default='na', max_length=10, unique=True),
        ),
    ]
