# Generated by Django 2.1.15 on 2020-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
