# Generated by Django 2.1.15 on 2020-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201114_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID',
            field=models.CharField(max_length=10),
        ),
    ]
