# Generated by Django 2.1.15 on 2020-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201114_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
