# Generated by Django 2.1.15 on 2020-11-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201114_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ID',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
