# Generated by Django 2.1.15 on 2020-12-06 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_data', '0001_initial'),
        ('accounts', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('rated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'assigned_task',
            },
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rater',
            },
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='rater',
            field=models.ForeignKey(db_column='rater', default=None, on_delete=django.db.models.deletion.CASCADE, to='rater.Rater'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='raw_data',
            field=models.ForeignKey(db_column='raw_data_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='raw_data.RawDataSeqFile'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task'),
        ),
    ]
