# Generated by Django 3.1.2 on 2020-11-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='rated_tasks',
            field=models.CharField(default='TEMp', max_length=100),
        ),
    ]
