# Generated by Django 2.1.15 on 2020-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
