# Generated by Django 2.1.15 on 2020-11-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0003_auto_20201128_1725'),
        ('task', '0001_initial'),
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('rater', models.ForeignKey(db_column='rater', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rater.Rater')),
                ('raw_data', models.ForeignKey(db_column='raw_data_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='raw_data.RawDataSeqFile')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
            options={
                'db_table': 'assigned_task',
            },
        ),
    ]
