# Generated by Django 3.1.2 on 2020-11-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_rater_rated_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='rated_tasks',
        ),
    ]
