# Generated by Django 2.1.15 on 2020-12-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('my_admin', '0001_initial'),
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataSeqFile',
            fields=[
                ('file', models.FileField(null=True, upload_to='')),
                ('seqnumber', models.AutoField(primary_key=True, serialize=False)),
                ('term_start', models.DateField(null=True)),
                ('term_end', models.DateField(null=True)),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'raw_data_seq_file',
            },
        ),
        migrations.CreateModel(
            name='RawDataType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30, unique=True)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='my_admin.MyAdmin')),
                ('task', models.ForeignKey(db_column='task', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
            options={
                'db_table': 'raw_data_type',
            },
        ),
        migrations.CreateModel(
            name='RawDataTypeSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('field_type', models.CharField(choices=[('char', 'Char'), ('int', 'Int'), ('date', 'Date'), ('boolean', 'Boolean')], default='na', max_length=30)),
                ('null_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='na', max_length=10)),
                ('mapping_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskDataTableSchema')),
                ('type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='raw_data.RawDataType')),
            ],
            options={
                'db_table': 'raw_data_type_schema',
            },
        ),
        migrations.AddField(
            model_name='rawdataseqfile',
            name='raw_data_type',
            field=models.ForeignKey(db_column='raw_data_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='raw_data.RawDataType'),
        ),
        migrations.AddField(
            model_name='rawdataseqfile',
            name='submitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
    ]
