# Generated by Django 3.1.2 on 2020-11-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('raw_id', models.AutoField(primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=5)),
                ('ordinal', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.submitter')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
