# Generated by Django 2.1.15 on 2020-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataseqfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
