# Generated by Django 2.1.15 on 2020-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('submitter', '0001_initial'),
        ('raw_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
