# Generated by Django 2.1.15 on 2020-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0002_rawdataseqfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdataseqfile',
            name='term',
        ),
        migrations.AddField(
            model_name='rawdataseqfile',
            name='term_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rawdataseqfile',
            name='term_start',
            field=models.DateField(null=True),
        ),
    ]
