# Generated by Django 2.1.15 on 2020-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0002_rawdatatypeschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdataseqfile',
            name='submitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='submitter.Submitter'),
        ),
        migrations.AlterField(
            model_name='rawdatatypeschema',
            name='mapping_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskDataTableSchema'),
        ),
    ]
