# Generated by Django 2.1.15 on 2020-12-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201206_1429'),
        ('raw_data', '0002_auto_20201206_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataTypeRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('task', models.ForeignKey(db_column='task', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task')),
            ],
            options={
                'db_table': 'raw_data_type_request',
            },
        ),
    ]
