# Generated by Django 2.1.15 on 2020-11-29 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0003_auto_20201128_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatatype',
            name='task',
            field=models.ForeignKey(db_column='task', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task'),
        ),
    ]
